# Installs
bash_tools_base_install: true
rust_install: true
starship_install: true
bash_tools_lazygit_install: true

# Rust variables (if installing via cargo)
rust_channel: stable
rust_profile: minimal
rust_install_path: "{{ ansible_user_dir }}/.cargo"
