---
extends: default

rules:
  truthy:
    allowed-values: ["yes", "no", "True", "false", "False", "true"]
  line-length:
    max: 300
    level: warning
  indentation: disable
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
