---

- name: workstation
  hosts: all
  
  roles:
  
    - role: bash_tools
      tags: 
        - base
      
    - role: rust
      tags:
        - rust
        
    - role: starship
      tags:
        - starship
        