---
- name: Workstation
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
      tags:
        - docker
        - skip_ansible_lint

    - role: geerlingguy.docker_arm
      when: ansible_architecture == "aarch64"
      tags:
        - docker_arm
        - skip_ansible_lint

    - role: bash_tools
      when:
        - base_install is true

    - role: rust
      when:
        - rust_install is true

    - role: starship
      when:
        - starship_install is true

    - role: pluggero.lazygit
      when:
        - lazygit_install is true
