---

- name: workstation
  hosts: all
  
  roles:
  
    - role: bash-tools
    
    - role: rust
      tags:
        - rust
        
    - role: starship
      tags:
        - starship
        