rust_targets: []
rust_components: []
rust_user: "{{ ansible_user }}"
rust_update: false
rust_install_dependencies: true

rust_cargo:
  packages:
    - cargo-binutils
    - cargo-binstall

rust_binstall:
  packages:
    - cargo-flash
    - cargo-generate
