---
# Starship role default variables
starship_install_method: script  # script, package, cargo
starship_config_dir: "{{ ansible_user_dir }}/.config"
starship_config_file: "{{ starship_config_dir }}/starship.toml"
starship_shells: ['bash']
starship_custom_config: false
starship_install_dependencies: true